// <auto-generated />
using System;
using InternalControl.Core.Core;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InternalControl.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200220072614_004")]
    partial class _004
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InternalControl.Core.Models.GroupOfIndicatorsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeOfFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeOfFormId");

                    b.ToTable("GroupOfIndicators");
                });

            modelBuilder.Entity("InternalControl.Core.Models.IndicatorsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupOfIndicatorsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TypeOfFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupOfIndicatorsId");

                    b.HasIndex("TypeOfFormId");

                    b.ToTable("Indicators");
                });

            modelBuilder.Entity("InternalControl.Core.Models.QuestionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupOfIndicatorsId")
                        .HasColumnType("int");

                    b.Property<int?>("IndicatorsId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypeOfFormId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupOfIndicatorsId");

                    b.HasIndex("IndicatorsId");

                    b.HasIndex("TypeOfFormId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("InternalControl.Core.Models.TypeOfForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TypeOfForm");
                });

            modelBuilder.Entity("InternalControl.Core.Models.GroupOfIndicatorsModel", b =>
                {
                    b.HasOne("InternalControl.Core.Models.TypeOfForm", "TypeOfForm")
                        .WithMany()
                        .HasForeignKey("TypeOfFormId");
                });

            modelBuilder.Entity("InternalControl.Core.Models.IndicatorsModel", b =>
                {
                    b.HasOne("InternalControl.Core.Models.GroupOfIndicatorsModel", "GroupOfIndicators")
                        .WithMany()
                        .HasForeignKey("GroupOfIndicatorsId");

                    b.HasOne("InternalControl.Core.Models.TypeOfForm", "TypeOfForm")
                        .WithMany()
                        .HasForeignKey("TypeOfFormId");
                });

            modelBuilder.Entity("InternalControl.Core.Models.QuestionModel", b =>
                {
                    b.HasOne("InternalControl.Core.Models.GroupOfIndicatorsModel", "GroupOfIndicators")
                        .WithMany()
                        .HasForeignKey("GroupOfIndicatorsId");

                    b.HasOne("InternalControl.Core.Models.IndicatorsModel", "Indicators")
                        .WithMany()
                        .HasForeignKey("IndicatorsId");

                    b.HasOne("InternalControl.Core.Models.TypeOfForm", "TypeOfForm")
                        .WithMany()
                        .HasForeignKey("TypeOfFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
